//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


[System.SerializableAttribute()]
[XmlRootAttribute("test-suite", Namespace="", IsNullable=false)]
public class TestSuite {
    
    private TestCase[] testCasesField;
    
    private TestSuite[] nestedTestSuiteField;
    
    private TestEnvironment[] environmentField;
    
    private testsuiteSettingsSetting[] settingsField;
    
    private testsuitePropertiesProperty[] propertiesField;
    
    private string typeField;
    
    private string idField;
    
    private string nameField;
    
    private string fullnameField;
    
    private string classnameField;
    
    private string runstateField;
    
    private string testcasecountField;
    
    private string resultField;
    
    private string starttimeField;
    
    private string endtimeField;
    
    private string durationField;
    
    private string totalField;
    
    private string passedField;
    
    private string failedField;
    
    private string warningsField;
    
    private string inconclusiveField;
    
    private string skippedField;
    
    private string assertsField;


    //[XmlElementAttribute("test-case", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlElement("test-case")]
    public TestCase[] TestCases {
        get {
            return this.testCasesField;
        }
        set {
            this.testCasesField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("test-suite")]
    public TestSuite[] NestedTestSuite {
        get {
            return this.nestedTestSuiteField;
        }
        set {
            this.nestedTestSuiteField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute("environment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TestEnvironment[] environment {
        get {
            return this.environmentField;
        }
        set {
            this.environmentField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("setting", typeof(testsuiteSettingsSetting), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public testsuiteSettingsSetting[] settings {
        get {
            return this.settingsField;
        }
        set {
            this.settingsField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [XmlArrayItemAttribute("property", typeof(testsuitePropertiesProperty), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public testsuitePropertiesProperty[] properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string fullname {
        get {
            return this.fullnameField;
        }
        set {
            this.fullnameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string classname {
        get {
            return this.classnameField;
        }
        set {
            this.classnameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string runstate {
        get {
            return this.runstateField;
        }
        set {
            this.runstateField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string testcasecount {
        get {
            return this.testcasecountField;
        }
        set {
            this.testcasecountField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("start-time")]
    public string starttime {
        get {
            return this.starttimeField;
        }
        set {
            this.starttimeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("end-time")]
    public string endtime {
        get {
            return this.endtimeField;
        }
        set {
            this.endtimeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string passed {
        get {
            return this.passedField;
        }
        set {
            this.passedField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string warnings {
        get {
            return this.warningsField;
        }
        set {
            this.warningsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string inconclusive {
        get {
            return this.inconclusiveField;
        }
        set {
            this.inconclusiveField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string skipped {
        get {
            return this.skippedField;
        }
        set {
            this.skippedField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string asserts {
        get {
            return this.assertsField;
        }
        set {
            this.assertsField = value;
        }
    }
}

[System.SerializableAttribute()]
[XmlTypeAttribute(AnonymousType = true)]
[XmlRootAttribute("test-case", Namespace = "", IsNullable = false)]
public class TestCase {
    
    private string idField;
    
    private string nameField;
    
    private string fullnameField;
    
    private string methodnameField;
    
    private string classnameField;
    
    private string runstateField;
    
    private string seedField;
    
    private string resultField;
    
    private string starttimeField;
    
    private string endtimeField;
    
    private string durationField;
    
    private string assertsField;
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string fullname {
        get {
            return this.fullnameField;
        }
        set {
            this.fullnameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string methodname {
        get {
            return this.methodnameField;
        }
        set {
            this.methodnameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string classname {
        get {
            return this.classnameField;
        }
        set {
            this.classnameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string runstate {
        get {
            return this.runstateField;
        }
        set {
            this.runstateField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string seed {
        get {
            return this.seedField;
        }
        set {
            this.seedField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("start-time")]
    public string starttime {
        get {
            return this.starttimeField;
        }
        set {
            this.starttimeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("end-time")]
    public string endtime {
        get {
            return this.endtimeField;
        }
        set {
            this.endtimeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string asserts {
        get {
            return this.assertsField;
        }
        set {
            this.assertsField = value;
        }
    }
}

[System.SerializableAttribute()]
[XmlTypeAttribute(AnonymousType=true)]
public class TestEnvironment {
    
    private string frameworkversionField;
    
    private string clrversionField;
    
    private string osversionField;
    
    private string platformField;
    
    private string cwdField;
    
    private string machinenameField;
    
    private string userField;
    
    private string userdomainField;
    
    private string cultureField;
    
    private string uicultureField;
    
    private string osarchitectureField;
    
    /// <remarks/>
    [XmlAttributeAttribute("framework-version")]
    public string frameworkversion {
        get {
            return this.frameworkversionField;
        }
        set {
            this.frameworkversionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("clr-version")]
    public string clrversion {
        get {
            return this.clrversionField;
        }
        set {
            this.clrversionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("os-version")]
    public string osversion {
        get {
            return this.osversionField;
        }
        set {
            this.osversionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string platform {
        get {
            return this.platformField;
        }
        set {
            this.platformField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string cwd {
        get {
            return this.cwdField;
        }
        set {
            this.cwdField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("machine-name")]
    public string machinename {
        get {
            return this.machinenameField;
        }
        set {
            this.machinenameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("user-domain")]
    public string userdomain {
        get {
            return this.userdomainField;
        }
        set {
            this.userdomainField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string culture {
        get {
            return this.cultureField;
        }
        set {
            this.cultureField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string uiculture {
        get {
            return this.uicultureField;
        }
        set {
            this.uicultureField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("os-architecture")]
    public string osarchitecture {
        get {
            return this.osarchitectureField;
        }
        set {
            this.osarchitectureField = value;
        }
    }
}

[System.SerializableAttribute()]
[XmlTypeAttribute(AnonymousType=true)]
public partial class testsuiteSettingsSetting {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

[System.SerializableAttribute()]
[XmlTypeAttribute(AnonymousType=true)]
public partial class testsuitePropertiesProperty {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}


[System.SerializableAttribute()]
[XmlTypeAttribute(AnonymousType=true)]
[XmlRootAttribute("test-run", Namespace="", IsNullable=false)]
public class TestRun {
    
    private string commandlineField;
    
    private TestSuite[] testsuiteField;
    
    private string idField;
    
    private string nameField;
    
    private string fullnameField;
    
    private string runstateField;
    
    private string testcasecountField;
    
    private string resultField;
    
    private string totalField;
    
    private string passedField;
    
    private string failedField;
    
    private string inconclusiveField;
    
    private string skippedField;
    
    private string assertsField;
    
    private string engineversionField;
    
    private string clrversionField;
    
    private string starttimeField;
    
    private string endtimeField;
    
    private string durationField;
    
    /// <remarks/>
    [XmlElementAttribute("command-line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CommandLine {
        get {
            return this.commandlineField;
        }
        set {
            this.commandlineField = value;
        }
    }

    /// <remarks/>
    //[XmlElementAttribute("test-suite")]
    [XmlElement("test-suite")]
    public TestSuite[] TestSuite {
        get {
            return this.testsuiteField;
        }
        set {
            this.testsuiteField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string fullname {
        get {
            return this.fullnameField;
        }
        set {
            this.fullnameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string runstate {
        get {
            return this.runstateField;
        }
        set {
            this.runstateField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string testcasecount {
        get {
            return this.testcasecountField;
        }
        set {
            this.testcasecountField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string passed {
        get {
            return this.passedField;
        }
        set {
            this.passedField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string inconclusive {
        get {
            return this.inconclusiveField;
        }
        set {
            this.inconclusiveField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string skipped {
        get {
            return this.skippedField;
        }
        set {
            this.skippedField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string asserts {
        get {
            return this.assertsField;
        }
        set {
            this.assertsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("engine-version")]
    public string engineversion {
        get {
            return this.engineversionField;
        }
        set {
            this.engineversionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("clr-version")]
    public string clrversion {
        get {
            return this.clrversionField;
        }
        set {
            this.clrversionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("start-time")]
    public string starttime {
        get {
            return this.starttimeField;
        }
        set {
            this.starttimeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute("end-time")]
    public string endtime {
        get {
            return this.endtimeField;
        }
        set {
            this.endtimeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
}

//[System.SerializableAttribute()]
//[XmlTypeAttribute(AnonymousType=true)]
//[XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class NewDataSet {
    
//    private object[] itemsField;
    
//    /// <remarks/>
//    [XmlElementAttribute("test-run", typeof(testrun))]
//    [XmlElementAttribute("test-suite", typeof(testsuite))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
